import{a as h,S as v,i as n}from"./assets/vendor-xpOxgMII.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&d(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function d(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const q="54439689-be74ec06959a2901216bd7b02";h.defaults.baseURL="https://pixabay.com/api";async function m(s,r=1){try{return await h.get("/",{params:{key:q,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}})}catch(e){throw console.error("Error fetching images from Pixabay API:",e),e}}const g=document.querySelector(".gallery");let i=null;function p(s){const r=s.map(e=>`
    <a class="gallery-item" href="${e.largeImageURL}">
      <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      <div class="gallery-info">
        <p class="gallery-info-item"><b>Likes:</b> ${e.likes}</p>
        <p class="gallery-info-item"><b>Views:</b> ${e.views}</p>
        <p class="gallery-info-item"><b>Comments:</b> ${e.comments}</p>
        <p class="gallery-info-item"><b>Downloads:</b> ${e.downloads}</p>
      </div>
    </a>
  `).join("");g.insertAdjacentHTML("beforeend",r),i?i.refresh():i=new v(".gallery a",{captionsData:"alt",captionDelay:250,showCounter:!0,overlayOpacity:.8})}function S(){g.innerHTML="",i&&i.refresh()}const y=document.querySelector(".loader-container");function b(){y.classList.remove("is-hidden")}function c(){y.classList.add("is-hidden")}const L=document.querySelector(".load-more-btn");function R(){L.classList.remove("is-hidden")}function w(){L.classList.add("is-hidden")}const P=document.querySelector("form"),f=document.querySelector('input[name="search-text"]');let a="",u=1;P.addEventListener("submit",E);async function E(s){if(s.preventDefault(),S(),w(),u=1,a=f.value.trim(),f.value="",a===""){n.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}b();try{const e=(await m(a)).data.hits;if(c(),e.length===0){n.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(e),R()}catch(r){c(),n.error({title:"Error",message:"An error occurred while fetching images.",position:"topRight"}),console.error(r)}}const B=document.querySelector(".load-more-btn");B.addEventListener("click",M);async function M(){b();try{u+=1;const s=document.querySelector(".gallery-item").getBoundingClientRect().height,e=(await m(a,u)).data.hits;if(c(),e.length===0){w(),n.info({title:"End of Results",message:"We're sorry, but you've reached the end of the search results.",position:"topRight"});return}p(e),window.scrollBy({top:s*2,behavior:"smooth"})}catch(s){c(),n.error({title:"Error",message:"An error occurred while fetching more images.",position:"topRight"}),console.error(s)}}document.querySelector(".gallery-item").getBoundingClientRect().height;
//# sourceMappingURL=index.js.map
