import{a as m,S,i as n}from"./assets/vendor-xpOxgMII.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))d(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const f of o.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&d(f)}).observe(document,{childList:!0,subtree:!0});function e(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function d(r){if(r.ep)return;r.ep=!0;const o=e(r);fetch(r.href,o)}})();const E="54439689-be74ec06959a2901216bd7b02";m.defaults.baseURL="https://pixabay.com/api";async function p(s,t=1){try{return await m.get("/",{params:{key:E,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})}catch(e){throw console.error("Error fetching images from Pixabay API:",e),e}}const g=document.querySelector(".gallery");let i=null;function y(s){const t=s.map(e=>`
    <a class="gallery-item" href="${e.largeImageURL}">
      <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      <div class="gallery-info">
        <p class="gallery-info-item"><b>Likes:</b> ${e.likes}</p>
        <p class="gallery-info-item"><b>Views:</b> ${e.views}</p>
        <p class="gallery-info-item"><b>Comments:</b> ${e.comments}</p>
        <p class="gallery-info-item"><b>Downloads:</b> ${e.downloads}</p>
      </div>
    </a>
  `).join("");g.insertAdjacentHTML("beforeend",t),i?i.refresh():i=new S(".gallery a",{captionsData:"alt",captionDelay:250,showCounter:!0,overlayOpacity:.8})}function P(){g.innerHTML="",i&&i.refresh()}const b=document.querySelector(".loader-container");function L(){b.classList.remove("is-hidden")}function u(){b.classList.add("is-hidden")}const w=document.querySelector(".load-more-btn");function v(){w.classList.remove("is-hidden")}function R(){w.classList.add("is-hidden")}const I=document.querySelector("form"),h=document.querySelector('input[name="search-text"]'),M=document.querySelector(".load-more-btn");let a="",l=1,c=0;const q=15;I.addEventListener("submit",$);M.addEventListener("click",B);async function $(s){if(s.preventDefault(),P(),R(),l=1,a=h.value.trim(),h.value="",a===""){n.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}L();try{const t=await p(a),e=t.data.hits;if(c=t.data.totalHits,u(),e.length===0){n.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(e),c>q?v():c>0&&n.info({title:"End of Results",message:"We're sorry, but you've reached the end of the search results.",position:"topRight"})}catch(t){u(),n.error({title:"Error",message:"An error occurred while fetching images.",position:"topRight"}),console.error(t)}}async function B(){R(),L();try{l+=1;const t=(await p(a,l)).data.hits;if(u(),t.length===0){n.info({title:"End of Results",message:"We're sorry, but you've reached the end of the search results.",position:"topRight"});return}y(t);const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"}),l*q<c?v():n.info({title:"End of Results",message:"We're sorry, but you've reached the end of the search results.",position:"topRight"})}catch(s){u(),n.error({title:"Error",message:"An error occurred while fetching more images.",position:"topRight"}),console.error(s)}}
//# sourceMappingURL=index.js.map
